---
image: "buluma/github-action-molecule:4.0.6"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  retry: 1
  parallel:
    matrix:
      - image: "debian-systemd"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "debian-systemd"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

role_testing:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.docker_ce
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 1
  parallel:
    matrix:
      - image: "debian-systemd"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"

galaxy:
  script:
    - ansible-galaxy role info buluma.docker_ce

role_testing_live:
  script:
    - image=${image} tag=${tag} ansible-galaxy install buluma.docker_ce
  retry: 1
  parallel:
    matrix:
      - image: "debian-systemd"
        tag: "latest"
      - image: "enterpriselinux"
        tag: "latest"
      - image: "fedora-systemd"
        tag: "34"
      - image: "fedora-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "latest"
      - image: "docker-ubuntu-systemd"
        tag: "bionic"
      - image: "docker-ubuntu-systemd"
        tag: "focal"
